CREATE TABLE pedidos
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id     BIGINT                                  NOT NULL,
    local_id       BIGINT                                  NOT NULL,
    fecha_creacion TIMESTAMPTZ                             NOT NULL,
    fecha_recojo   TIMESTAMPTZ,
    estado         VARCHAR(30)                             NOT NULL,
    metodo_pago    VARCHAR(30)                             NOT NULL,
    total          DECIMAL(10, 2)                          NOT NULL,

    CONSTRAINT pk_pedidos
        PRIMARY KEY (id),

    CONSTRAINT fk_pedidos_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id),

    CONSTRAINT fk_pedidos_local
        FOREIGN KEY (local_id)
        REFERENCES locales (id),

    CONSTRAINT chk_pedidos_estado
        CHECK (estado IN ('RECIBIDO', 'PREPARANDO', 'LISTO', 'ENTREGADO', 'CANCELADO')),

    CONSTRAINT chk_pedidos_metodo_pago
        CHECK (metodo_pago IN ('CASH', 'CARD', 'PAYPAL')),

    CONSTRAINT chk_pedidos_total
        CHECK (total >= 0)
);

CREATE INDEX idx_pedidos_usuario
    ON pedidos (usuario_id);
