CREATE TABLE pedido_detalles
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pedido_id        BIGINT                                  NOT NULL,
    producto_id      BIGINT                                  NOT NULL,
    producto_size_id BIGINT                                  NOT NULL,
    milk_id          BIGINT,
    cream_id         BIGINT,
    caffeine_id      BIGINT,
    nombre_producto  VARCHAR(255)                            NOT NULL,
    cantidad         INTEGER                                 NOT NULL,
    precio_unitario  DECIMAL(10, 2)                          NOT NULL,
    total            DECIMAL(10, 2)                          NOT NULL,

    CONSTRAINT pk_pedido_detalles
        PRIMARY KEY (id),

    CONSTRAINT fk_pedido_detalles_pedido
        FOREIGN KEY (pedido_id)
        REFERENCES pedidos (id),

    CONSTRAINT fk_pedido_detalles_producto
        FOREIGN KEY (producto_id)
        REFERENCES productos (id),

    CONSTRAINT fk_pedido_detalles_producto_size
        FOREIGN KEY (producto_size_id)
        REFERENCES producto_sizes (id),

    CONSTRAINT fk_pedido_detalles_milk
        FOREIGN KEY (milk_id)
        REFERENCES opciones_personalizacion (id),

    CONSTRAINT fk_pedido_detalles_cream
        FOREIGN KEY (cream_id)
        REFERENCES opciones_personalizacion (id),

    CONSTRAINT fk_pedido_detalles_caffeine
        FOREIGN KEY (caffeine_id)
        REFERENCES opciones_personalizacion (id),

    CONSTRAINT chk_pedido_detalles_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_pedido_detalles_precio_unitario
        CHECK (precio_unitario >= 0),

    CONSTRAINT chk_pedido_detalles_total
        CHECK (total >= 0)
);

CREATE INDEX idx_pedido_detalles_pedido
    ON pedido_detalles (pedido_id);
