CREATE TABLE favoritos
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id     BIGINT                                  NOT NULL,
    producto_id    BIGINT                                  NOT NULL,
    fecha_creacion TIMESTAMPTZ                             NOT NULL,

    CONSTRAINT pk_favoritos
        PRIMARY KEY (id),

    CONSTRAINT fk_favoritos_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_favoritos_producto
        FOREIGN KEY (producto_id)
        REFERENCES productos (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_favoritos_usuario_producto
        UNIQUE (usuario_id, producto_id)
);

CREATE INDEX idx_favoritos_producto
    ON favoritos (producto_id);
