CREATE TABLE usuarios
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre              VARCHAR(255)                            NOT NULL,
    email               VARCHAR(255)                            NOT NULL,
    password_hash       VARCHAR(255),
    foto_url            VARCHAR(255),
    activo              BOOLEAN                                 NOT NULL,
    fecha_creacion      TIMESTAMPTZ                             NOT NULL,
    fecha_actualizacion TIMESTAMPTZ                             NOT NULL,

    CONSTRAINT pk_usuarios
        PRIMARY KEY (id),
    CONSTRAINT uc_usuarios_email
        UNIQUE (email)
);