CREATE TABLE codigo_verificacion
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo              VARCHAR(64)                             NOT NULL,
    estado              VARCHAR(30)                             NOT NULL,
    fecha_expiracion    TIMESTAMPTZ                             NOT NULL,
    fecha_creacion      TIMESTAMPTZ                             NOT NULL,
    fecha_actualizacion TIMESTAMPTZ                             NOT NULL,
    usuario_id          BIGINT                                  NOT NULL,

    CONSTRAINT pk_codigo_verificacion
        PRIMARY KEY (id),

    CONSTRAINT fk_codigo_verificacion_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_codigo_verificacion_estado
        CHECK (estado IN('VIGENTE', 'USADO', 'EXPIRADO'))
);

CREATE INDEX idx_codigo_verificacion_usuario
    ON codigo_verificacion (usuario_id);

CREATE INDEX idx_codigo_verificacion_busqueda
    ON codigo_verificacion (usuario_id, codigo, estado);
