CREATE TABLE codigo_verificaciones
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo              VARCHAR(64)                             NOT NULL,
    estado              VARCHAR(30)                             NOT NULL,
    fecha_expiracion    TIMESTAMPTZ                             NOT NULL,
    fecha_creacion      TIMESTAMPTZ                             NOT NULL,
    fecha_actualizacion TIMESTAMPTZ                             NOT NULL,
    usuario_id          BIGINT                                  NOT NULL,

    CONSTRAINT pk_codigo_verificaciones
        PRIMARY KEY (id),

    CONSTRAINT fk_codigo_verificaciones_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_codigo_verificaciones_estado
        CHECK (estado IN('VIGENTE', 'USADO', 'EXPIRADO'))
);

CREATE INDEX idx_codigo_verificaciones_usuario
    ON codigo_verificaciones (usuario_id);

CREATE INDEX idx_codigo_verificaciones_busqueda
    ON codigo_verificaciones (usuario_id, codigo, estado);
