CREATE TABLE cuenta_social
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_proveedor   VARCHAR(255)                            NOT NULL,
    proveedor      VARCHAR(255)                            NOT NULL,
    id_usuario     BIGINT                                  NOT NULL,
    fecha_creacion TIMESTAMPTZ                             NOT NULL,

    CONSTRAINT pk_cuenta_social
        PRIMARY KEY (id),

    CONSTRAINT fk_cuenta_social_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_cuenta_social_proveedor_id
        UNIQUE (proveedor, id_proveedor)
);

CREATE INDEX idx_cuenta_social_usuario
    ON cuenta_social (id_usuario);