CREATE TABLE cuentas_sociales
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_proveedor   VARCHAR(255)                            NOT NULL,
    proveedor      VARCHAR(255)                            NOT NULL,
    id_usuario     BIGINT                                  NOT NULL,
    fecha_creacion TIMESTAMPTZ                             NOT NULL,

    CONSTRAINT pk_cuentas_sociales
        PRIMARY KEY (id),

    CONSTRAINT fk_cuentas_sociales_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_cuentas_sociales_proveedor_id
        UNIQUE (proveedor, id_proveedor)
);

CREATE INDEX idx_cuentas_sociales_usuario
    ON cuentas_sociales (id_usuario);