CREATE TABLE categorias
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR(255)                            NOT NULL,
    orden  INTEGER                                 NOT NULL,

    CONSTRAINT pk_categorias
        PRIMARY KEY (id)
);