CREATE TABLE productos
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre         VARCHAR(255)                            NOT NULL,
    descripcion    TEXT                                    NOT NULL,
    imagen_url     TEXT,
    nuevo          BOOLEAN                                 NOT NULL,
    frecuente      BOOLEAN                                 NOT NULL,
    disponible     BOOLEAN                                 NOT NULL,
    personalizable BOOLEAN                                 NOT NULL,
    categoria_id   BIGINT                                  NOT NULL,

    CONSTRAINT pk_productos
        PRIMARY KEY (id),
    CONSTRAINT fk_productos_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categorias (id)
);