CREATE TABLE producto_sizes
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre         VARCHAR(255)                            NOT NULL,
    precio         DECIMAL(10, 2)                          NOT NULL,
    predeterminado BOOLEAN                                 NOT NULL,
    producto_id    BIGINT                                  NOT NULL,

    CONSTRAINT pk_producto_sizes
        PRIMARY KEY (id),

    CONSTRAINT fk_productos_sizes_producto
        FOREIGN KEY (producto_id)
        REFERENCES productos (id),

    CONSTRAINT chk_nombre_producto_sizes
        CHECK ( nombre IN('SMALL', 'MEDIUM', 'LARGE', 'UNICO') ),

    CONSTRAINT chk_precio_producto_sizes
        CHECK ( precio >= 0 ),

    CONSTRAINT uk_producto_sizes_producto_id
        UNIQUE (nombre, producto_id)
);
