CREATE TABLE opciones_personalizacion
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo           VARCHAR(255)                            NOT NULL,
    nombre         VARCHAR(255)                            NOT NULL,
    precio_extra   DECIMAL(10, 2)                          NOT NULL,
    predeterminada BOOLEAN                                 NOT NULL,
    activo         BOOLEAN                                 NOT NULL,

    CONSTRAINT pk_opciones_personalizacion
        PRIMARY KEY (id),

    CONSTRAINT chk_tipo_opciones_personalizacion
        CHECK ( tipo IN ('MILK', 'CREAM', 'CAFFEINE') ),

    CONSTRAINT chk_precio_extra_opciones_personalizacion
        CHECK ( precio_extra >= 0 )
);