CREATE TABLE distritos
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_distritos
        PRIMARY KEY (id)
);