CREATE TABLE locales
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre      VARCHAR(255)                            NOT NULL,
    direccion   VARCHAR(255)                            NOT NULL,
    horario     VARCHAR(255)                            NOT NULL,
    latitud     DECIMAL(10, 7)                          NOT NULL,
    longitud    DECIMAL(10, 7)                          NOT NULL,
    activo      BOOLEAN                                 NOT NULL,
    frecuente   BOOLEAN                                 NOT NULL DEFAULT FALSE,
    distrito_id BIGINT                                  NOT NULL,

    CONSTRAINT pk_locales
        PRIMARY KEY (id),

    CONSTRAINT fk_locales_distrito
        FOREIGN KEY (distrito_id)
            REFERENCES distritos (id)
);

CREATE INDEX idx_locales_distrito
    ON locales (distrito_id);
